-- Eloria — initial schema
-- Apply by pasting into Supabase Dashboard → SQL Editor → Run.

-- ============================================================
-- CATEGORIES
-- ============================================================
create table if not exists categories (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name_en text not null,
  name_sl text,
  position int not null default 0,
  created_at timestamptz not null default now()
);

-- ============================================================
-- PRODUCTS
-- ============================================================
create table if not exists products (
  id bigint generated by default as identity primary key,
  woo_id bigint unique,
  slug text unique not null,
  name_en text not null,
  name_sl text,
  short_description_en text,
  short_description_sl text,
  price numeric(10,2) not null,
  compare_price numeric(10,2),
  currency text not null default 'EUR',
  image text,
  badge text,
  emoji text,
  stock_status text not null default 'instock',
  stock_quantity int,
  age_min_months int,
  age_max_months int,
  permalink_en text,
  permalink_sl text,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_slug_idx on products(slug);
create index if not exists products_published_idx on products(is_published);

-- gallery images
create table if not exists product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  url text not null,
  position int not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists product_images_product_idx on product_images(product_id);

-- many-to-many: products <-> categories
create table if not exists product_categories (
  product_id bigint not null references products(id) on delete cascade,
  category_id bigint not null references categories(id) on delete cascade,
  primary key (product_id, category_id)
);

-- ============================================================
-- CUSTOMERS / ORDERS
-- ============================================================
create table if not exists customers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  name text,
  phone text,
  created_at timestamptz not null default now()
);
create index if not exists customers_email_idx on customers(email);

create sequence if not exists order_number_seq start 1000;

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null default ('ELO-' || to_char(now(),'YYYY') || '-' || lpad(nextval('order_number_seq')::text, 5, '0')),
  customer_id uuid references customers(id) on delete set null,
  email text not null,
  status text not null default 'pending',           -- pending | paid | fulfilled | cancelled | refunded
  payment_status text not null default 'pending',   -- pending | paid | failed | refunded
  shipping_status text not null default 'pending',  -- pending | shipped | delivered
  subtotal numeric(10,2) not null,
  shipping_cost numeric(10,2) not null default 0,
  tax numeric(10,2) not null default 0,
  total numeric(10,2) not null,
  currency text not null default 'EUR',
  shipping_address jsonb,
  billing_address jsonb,
  stripe_session_id text,
  stripe_payment_intent text,
  tracking_carrier text,
  tracking_number text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists orders_status_idx on orders(status);
create index if not exists orders_email_idx on orders(email);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references orders(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  product_name text not null,
  product_slug text,
  unit_price numeric(10,2) not null,
  quantity int not null,
  total numeric(10,2) not null,
  created_at timestamptz not null default now()
);
create index if not exists order_items_order_idx on order_items(order_id);

-- ============================================================
-- updated_at triggers
-- ============================================================
create or replace function set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists products_updated_at on products;
create trigger products_updated_at before update on products
  for each row execute function set_updated_at();

drop trigger if exists orders_updated_at on orders;
create trigger orders_updated_at before update on orders
  for each row execute function set_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY
-- Public catalog reads OK. Everything else only via service_role
-- (bypasses RLS automatically).
-- ============================================================
alter table categories          enable row level security;
alter table products            enable row level security;
alter table product_images      enable row level security;
alter table product_categories  enable row level security;
alter table customers           enable row level security;
alter table orders              enable row level security;
alter table order_items         enable row level security;

-- public read: catalog
drop policy if exists "public read categories" on categories;
create policy "public read categories" on categories for select using (true);

drop policy if exists "public read products" on products;
create policy "public read products" on products for select using (is_published = true);

drop policy if exists "public read product_images" on product_images;
create policy "public read product_images" on product_images for select using (true);

drop policy if exists "public read product_categories" on product_categories;
create policy "public read product_categories" on product_categories for select using (true);

-- customers/orders/order_items: no public policies (only service_role).
